url = "http://ftp.gnu.org/gnu/bash/bash-5.1.8.tar.gz"
supportsRosetta = true

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []

[intel]
checksum = ""

[silicon]
checksum = '4829447aa8d3faf7374ed7c8fdc3b7cf9a7b73140b340cef223af65963be27c9'
