url = 'https://github.com/pakket-project/pakket/archive/refs/tags/v0.0.1-alpha.1.tar.gz'
supportsRosetta = false
[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = ''

[silicon]
checksum = '8e684141987feec252c159bb93dbce09d070ccc6ebd858bd30051a0d08e52ed7'
