url = "https://www.openssl.org/source/openssl-1.1.1l.tar.gz"
supportsRosetta = false
[dependencies]
dependencies = ["generate-ca-certificates"]
buildDependencies = []
optionalDependencies = []

[intel]
checksum = '4725f703ad6cb0f1097978e4476389556c3d3c6f8a754d453012bcf59a3e2578'

[silicon]
checksum = 'f79df2575b4b7b6c1c8e78669d5cbaaf1630affd92c1c951d96205261eff9b59'
