url = "https://www.openssl.org/source/openssl-1.1.1l.tar.gz"
supportsRosetta = false
[dependencies]
dependencies = ["ca-certificates"]
buildDependencies = []
optionalDependencies = []

[intel]
checksum = ''

[silicon]
checksum = 'efe7509e4281998bebb371f6b1b3a10d58a72f36da3c762c91edd9e36e7ed8f2'
