url = "https://www.openssl.org/source/openssl-1.1.1l.tar.gz"
supportsRosetta = false
[dependencies]
dependencies = ["generate-ca-certificates"]
buildDependencies = []
optionalDependencies = []

[intel]
checksum = '0679ea1877643c0bdbe886a80d398ed70c05b0cbbf192cb463a1702c95640451'

[silicon]
checksum = 'f79df2575b4b7b6c1c8e78669d5cbaaf1630affd92c1c951d96205261eff9b59'
