url = 'https://github.com/wouter173/generate-ca-certificates/archive/refs/tags/1.0.tar.gz'
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = '2b0ad4ae4bd4104aec31a8103448a40fedadde2fe9f8b08d6cc1680a41d5c52a'

[silicon]
checksum = '7c67588245caafad48dbed3916b9464e602e3ec4c22414d01d3350ccb5a01172'
