url = 'https://github.com/wouter173/generate-ca-certificates/archive/refs/tags/1.0.tar.gz'
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = ''

[silicon]
checksum = 'cefe7c2d82d5fad84b87d2c030a501ba3bf4a7a96351acc6f0c4ee216675dc77'
