url = "https://github.com/htop-dev/htop/archive/3.0.5.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = ["ncurses"]
buildDependencies = [
  "autoconf",
  "automake",
  "libtool",
  "pkg-config",
  "python@3.9",
]
optionalDependencies = []

[intel]
checksum = "c99fd55934bf8ac6591ce184aadeac52bcb30d691a1d23328cbf6cbf31505d35"

[silicon]
checksum = "e45cbf51c82c98fca0fa3080c962f8c9521e1d4653e979babd307084b63bf8b4"
