url = 'https://github.com/pakket-project/builder/archive/refs/tags/v0.0.5.tar.gz'
[dependencies]

buildDependencies = [
  'go'
]


[amd64]


[arm64]
checksum = '9eeefec2f4cffee5df9cb1cb423f17f35850fc8fb6b12da56721a78e27be5b29'

