url = 'https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz'

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []

[intel]
checksum = '0b11076389c251732b6973a1cd969090d2f9fa110a18b4a08ddfad8ea5e6fdd0'

[silicon]
checksum = 'f57bf59c8dad0388707dca09f705268d0163cc4b4fc7aeba2b34ac32b7d03b66'
