url = "https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []


[intel]
checksum = ""

[silicon]
checksum = 'b839c8552e944adb2c084d62db0e196e5ef099434f02517e56437c1eab8662b5'
