url = 'https://ftp.gnu.org/gnu/readline/readline-8.1.tar.gz'
supportsRosetta = false
[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []

[intel]
checksum = '925e5efbdbec242f3d61afd9967e978a150f9d23507104e130e8645d79945642'

[silicon]
checksum = 'b499dc3a4efff9333e81f043350e77bcac21c471a25afadf48ac86c457d1a83c'

