[package]
name = "bat"
description = "Clone of cat(1) with syntax highlighting and Git integration"
license = "Apache-2.0"
version = "v0.18.0"
homepage = "https://github.com/sharkdp/bat"
url = "https://github.com/sharkdp/bat/archive/v0.18.0.tar.gz"
sha256 = "49d1b95250050df47753c213b5e48953a029c9e74753cef371051b14c9d629b8"
dependencies = [{name = "rust", optional = false, version = "latest", build = true}]

[binaries]
  [binaries.big_sur_arm] # Big Sur (arn)
  url = ""
  version = ""
  sha256 = ""
  available = false

  [binaries.big_sur] # Big Sur
  url = "https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-v0.18.0-x86_64-apple-darwin.tar.gz"
  binPath = "bat"
  version = "0.18.0"
  sha256 = "86583f06b490278fed45407f34afb17d674a8c8c6e8c70bcee5e9bcbf7f3f548"
  available = true

  [binaries.catalina] # Catalina
  url = "https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-v0.18.0-x86_64-apple-darwin.tar.gz"
  binPath = "bat"
  version = "0.18.0"
  sha256 = "86583f06b490278fed45407f34afb17d674a8c8c6e8c70bcee5e9bcbf7f3f548"
  available = true

  [binaries.mojave] # Mojave
  url = "https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-v0.18.0-x86_64-apple-darwin.tar.gz"
  binPath = "bat"
  version = "0.18.0"
  sha256 = "86583f06b490278fed45407f34afb17d674a8c8c6e8c70bcee5e9bcbf7f3f548"
  available = true
