url = 'https://github.com/pakket-project/builder/archive/refs/tags/v0.0.3.tar.gz'
supportsRosetta = false
[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = 'e9d30708ed9048ecc02d8f36ca5e88edf7c537fc98823091435317e7b29e149f'

[silicon]
checksum = '0243302ca18c79bd1e12d99245715130bc8faa0dafc902cd187da4c6ae312b54'
