name: "Build and push packages to mirror"

on:
  workflow_dispatch:
    inputs:
      PR:
        description: "PR number"
        required: false
      package:
        description: "Package name (if not PR)"
        required: false
      version:
        description: "Package version (if not PR)"
        required: false

jobs:
  builder:
    runs-on: "${{matrix.os}}"
    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ["self-hosted", "silicon"]
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"
            arch: "silicon"
          - os: ["self-hosted", "intel"]
            shell: "bash"
            arch: "intel"

    defaults:
      run:
        shell: "${{matrix.shell}}"

    steps:
      - name: "check arch"
        run: "arch"

      - name: "clean working directory"
        run: sudo rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.* || true

      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "setup pakket-builder"
        uses: pakket-project/actions/setup-builder@main
        with:
          version: "0.0.5"

      - name: "run pakket-builder"
        uses: pakket-project/actions/build@main
        with:
          PR: "${{ github.event.inputs.PR }}"
          package: "${{ github.event.inputs.package }}"
          version: "${{ github.event.inputs.version }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "clean working directory"
        run: sudo rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.* || true
