url = 'https://github.com/pakket-project/builder/archive/refs/tags/v0.0.1.tar.gz'
supportsRosetta = false
[dependencies]
dependencies = []
buildDependencies = ['go']
optionalDependencies = []

[intel]
checksum = '9bfffd418f55489cb8e2e4dffa50e33edf2a9201e89d5734b1cdffc1e36c7729'

[silicon]
checksum = 'bcaa3edf1a393d14636ec298d77fa0b7501125e2cbc792209c8740a2e3fcbdb0'

