url = "https://github.com/pakket-project/builder/archive/refs/tags/v0.0.1.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = ["go"]
optionalDependencies = []

[intel]
checksum = ""

[silicon]
checksum = '0566731c1798f4ae487bb6907c89da71b16fc03077a1a45148436b5945b8fe68'
