url = "https://github.com/tj/n/archive/refs/tags/v8.2.0.tar.gz"
supportsRosetta = false

[dependencies]
dependencies = []
buildDependencies = []
optionalDependencies = []

[intel]
checksum = '6b3a53d4a8d122eb470d0d6fe7525f751e64e5458131d7142fd233c9b7defe78'

[silicon]
checksum = 'e98b7dc103adf997fa7ec8c799d1a42b82501ebd0caa7290f95c2c9f5f82dd89'
